### ISSUE TITLE
What format do we use to add industry standards ??

### ISSUE THREAD

**Issue by miqui** [OAI/sig-industry-standards#1]
Hi @darrelmiller 

So, I have a few things I can add in the Air line space as it pertains to OpenAPI.   How do we get started ? An simple table in md with a few pertinent headers?

Thanks
Miguel

**Comment by darrelmiller** [comment]
I think a markdown table seems like a reasonable place to start.  I would suggest something like:

| Organization | Description | Standards Used |
|-----|-----|-----|
| [Example Org](https://example.org) | Keeper of the example standards | OpenAPI v3.1, Arezzo v1.0 |

We could call the file `organizations.md`

**Comment by miqui** [comment]
Awesome.  Sounds like a plan. Thanks @darrelmiller
